FROM mcr.microsoft.com/dotnet/sdk:10.0 AS base
WORKDIR /app

COPY EvacuationAPI.csproj .
RUN dotnet restore --no-cache
COPY . .

ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile", "--non-interactive", "--urls", "http://0.0.0.0:8080"]
